// The Lab's positions — generated by inverting the algorithm, not chosen by me.
//
// ---------------------------------------------------------------------------
// Will, on the previous set:
//
//   "If the algorithm was working correctly then we should not have all these
//    erroneously constructed examples, because they would be generated by
//    inverting it."
//
// He was right, and the previous seven positions were all mine: hand-built to
// illustrate a mechanism, and all seven misconstructed — a pin repairable with
// tempo, a knight already one move from a fork, a pawn whose "attack" blocked
// the bishop behind it. When the same person writes the procedure and picks the
// positions it is judged on, the fixture inherits the error and the tests pass.
//
// These are produced by `scripts/invent.mjs`: random positions, the algorithm
// run on every black piece, Stockfish adjudicating each candidate, and the first
// position that lands in each CATEGORY kept. The categories are the algorithm's
// own outputs — it is hanging, one move of preparation wins, the prize walks, a
// defender arrives, something bigger interrupts, the defence is on loan — so the
// set is a picture of what the procedure can say rather than a gallery of what I
// hoped it would say.
//
// One position is still hand-built, and it is labelled: `origin: 'hand-built'`.
// The generator could not produce that category in 2,500 random positions, which
// is itself a result worth keeping — a preparing move whose knot survives EVERY
// legal reply is rare. Stockfish plays the algorithm's move in it.
//
// A seventh category was dropped rather than shipped. The generator offered a
// position for "it cannot run — something stands behind it", but the algorithm's
// headline for it was "take it now": the piece was loose as well as loaded, so
// the example would have demonstrated a mechanism its title never mentioned.
// That is the exact defect this whole exercise was about, and keeping it because
// it filled a slot would have been the same mistake in a new costume. The
// mechanism is visible in #2 instead, where the knight cannot step off without
// ♖d1×d8 collecting the queen behind it.
//
// The three rules that survived from the old set, each learned by getting it
// wrong: kings get a pawn shelter (a bare king invents defensive resources no
// real position has), material stays roughly level (so the engine is scoring the
// tactic and not an imbalance left lying around), and the claim comes from the
// engine rather than from me.
// ---------------------------------------------------------------------------

export type Preset = {
	/** Stable number, so a position can be referred to in one word. */
	n: number;
	/** Which of the algorithm's outputs this is an example of. */
	key: string;
	name: string;
	fen: string;
	target: string;
	/** What the position is for, in one line, for a reader at the board. */
	expect: string;
	/** Set by the engine: does the attacking side win material here? */
	claim?: 'wins' | 'nothing';
	/** The engine's evaluation when the claim was recorded. */
	engine?: string;
	/** Where the position came from. Stated, because it matters. */
	origin: 'generated' | 'hand-built';
};

export const PRESETS: Preset[] = [
	{
		n: 1,
		key: 'now',
		name: 'It is simply hanging',
		fen: '6k1/5ppp/1n2n3/P2q4/2Nb4/3nQpB1/NN3PPP/6K1 w - - 0 1',
		target: 'd3',
		expect:
			'The dull baseline, and it has to be here: everything is already in contact, so this is an exchange count and nothing more. SEE has answered this since the 1970s. Every position below asks the question this one cannot.',
		claim: 'wins',
		engine: '+221cp',
		origin: 'generated',
	},
	{
		n: 2,
		key: 'build',
		name: 'One move of preparation, and it cannot be answered',
		fen: '1r1q2k1/1p3ppp/4p3/3n4/8/N7/1P2PPPP/Q2R2K1 w - - 0 1',
		target: 'd5',
		expect:
			'The one position in this set I chose rather than found, and the generator is the reason it survives: in 2,500 random positions it never produced this category at all. A preparing move whose knot survives EVERY legal reply is rare, which is exactly why it is worth teaching. Stockfish plays the same first move.',
		claim: 'wins',
		engine: '+451cp',
		origin: 'hand-built',
	},
	{
		n: 3,
		key: 'escape',
		name: 'The count pays and the prize walks away',
		fen: '6k1/r4ppp/1r6/1q2b3/8/6QR/1B2RPPP/6K1 w - - 0 1',
		target: 'b5',
		expect:
			'The count says the exchange pays. It does not form, and the reason is the first of the three: the prize has the same tempo the plan was spending, and it spends it leaving.',
		claim: 'nothing',
		engine: '-349cp',
		origin: 'generated',
	},
	{
		n: 4,
		key: 'defender',
		name: 'The count pays and a defender arrives in time',
		fen: '6k1/1b3ppp/6R1/1b3P2/r4B2/3p4/3B1PPP/6K1 w - - 0 1',
		target: 'g7',
		expect:
			'The count says the exchange pays. It does not form, and the reason is the second of the three: a defender arrives inside the same tempo.',
		claim: 'nothing',
		engine: '+2cp',
		origin: 'generated',
	},
	{
		n: 5,
		key: 'forcing',
		name: 'The count pays and a bigger threat interrupts',
		fen: '6k1/5ppp/8/B3n1b1/N6b/BP1p4/5PPP/6K1 w - - 0 1',
		target: 'h4',
		expect:
			'The count says the exchange pays. It does not form, and the reason is the third: something bigger interrupts, and the tempo the plan was counting on is spent answering it.',
		claim: 'nothing',
		engine: '+67cp at depth 16',
		origin: 'generated',
	},
	{
		n: 6,
		key: 'entangled',
		name: 'The defence is on loan from somewhere else',
		fen: '6k1/1b3ppp/1q2bR2/1r1r4/7Q/1B1B4/2R2PPP/6K1 w - - 0 1',
		target: 'b7',
		expect:
			'Nothing wins outright, and the defence is still not sound: the piece holding this square is the only thing holding another one. Not a fork, not an overload, not a pin — one piece with two jobs, priced.',
		claim: 'nothing',
		engine: '+440cp overall — and nothing at b7, which is the point',
		origin: 'generated',
	},
];
