// How often is the contest algorithm right? Measured, on positions nobody chose.
//
// ---------------------------------------------------------------------------
// Will: "If the algorithm was working correctly then we should not have all
// these erroneously constructed examples, because they would be generated by
// inverting it."
//
// That is the test this project has never had. Seven hand-built fixtures prove
// nothing about an algorithm — especially when the same person builds the
// fixture and the algorithm, which is how every error in this thread survived a
// round of tests. So: GENERATE positions, run the algorithm, ask Stockfish, and
// count the disagreements.
//
// The generator is deliberately dumb. It places a random small set of pieces
// with a shelter for each king, keeps the material roughly level, and picks a
// square that at least one side bears on. No attempt is made to produce
// "interesting" positions, because choosing what is interesting is exactly the
// step that lets my assumptions back in.
//
// Usage:  node scripts/agree.mjs [count]
// ---------------------------------------------------------------------------

import { spawn } from 'node:child_process';
import { build } from 'esbuild';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const ENGINE = '/usr/games/stockfish';
const COUNT = Number(process.argv[2] ?? 60);
const DEPTH = 14;

// ---------------------------------------------------------------------------
// Load the app's own domain code, compiled on the fly. Reimplementing any of it
// here would test the reimplementation.
// ---------------------------------------------------------------------------
const dir = mkdtempSync(join(tmpdir(), 'agree-'));
const entry = join(dir, 'entry.ts');
writeFileSync(
	entry,
	`export { contest, VALUE } from ${JSON.stringify(join(process.cwd(), 'src/domain/contest.ts'))};
	 export { positionFromFen, makeSquare, parseSquare } from ${JSON.stringify(join(process.cwd(), 'src/domain/chess.ts'))};`,
);
const outfile = join(dir, 'bundle.mjs');
await build({ entryPoints: [entry], bundle: true, format: 'esm', outfile, platform: 'node', logLevel: 'silent' });
const { contest, positionFromFen, VALUE } = await import(outfile);

// ---------------------------------------------------------------------------
// A random position: kings with a pawn shelter, then a few pieces each.
// ---------------------------------------------------------------------------
const FILES = 'abcdefgh';
const sq = (f, r) => `${FILES[f]}${r + 1}`;

function randomPosition(rng) {
	const board = new Map();
	// Castled kings with three pawns each — a bare king invents defensive
	// resources that no real position has, which is how the first fixture set
	// went wrong.
	board.set('g1', 'K');
	board.set('g8', 'k');
	for (const f of [5, 6, 7]) {
		board.set(sq(f, 1), 'P');
		board.set(sq(f, 6), 'p');
	}

	const roles = ['Q', 'R', 'R', 'B', 'B', 'N', 'N', 'P', 'P', 'P'];
	const n = 3 + Math.floor(rng() * 4);
	const chosen = [];
	for (let i = 0; i < n; i++) chosen.push(roles[Math.floor(rng() * roles.length)]);

	for (const role of chosen) {
		for (const [colour, side] of [
			['w', role],
			['b', role.toLowerCase()],
		]) {
			for (let tries = 0; tries < 40; tries++) {
				const f = Math.floor(rng() * 8);
				// Keep pawns off the back ranks and pieces out of the shelters.
				const r = colour === 'w' ? 1 + Math.floor(rng() * 5) : 2 + Math.floor(rng() * 5);
				const key = sq(f, r);
				if (board.has(key)) continue;
				if (side.toUpperCase() === 'P' && (r === 0 || r === 7)) continue;
				board.set(key, side);
				break;
			}
		}
	}

	const rows = [];
	for (let r = 7; r >= 0; r--) {
		let row = '';
		let gap = 0;
		for (let f = 0; f < 8; f++) {
			const p = board.get(sq(f, r));
			if (!p) gap++;
			else {
				if (gap) row += gap;
				gap = 0;
				row += p;
			}
		}
		if (gap) row += gap;
		rows.push(row);
	}
	return `${rows.join('/')} w - - 0 1`;
}

/** Squares worth asking about: occupied by Black, and attacked by White. */
function targets(fen) {
	const pos = positionFromFen(fen);
	const out = [];
	for (let f = 0; f < 8; f++) {
		for (let r = 0; r < 8; r++) {
			const key = sq(f, r);
			const piece = pos.board.get(parse(key));
			if (!piece || piece.color !== 'black' || piece.role === 'king') continue;
			out.push(key);
		}
	}
	return out;
}
const parse = (s) => (Number(s[1]) - 1) * 8 + (FILES.indexOf(s[0]));

/**
 * Does the engine's own line win material AT THIS SQUARE, within `plies`?
 *
 * The first version of this asked whether the balance moved over the whole
 * variation, with a capture on the target somewhere in it. That is the same
 * mistake the algorithm was making — attributing material to a square because a
 * capture happened to land there. In one position it credited the square f7
 * with a bishop won on f5 two moves earlier.
 *
 * So: walk the line to the first capture on the target, take the balance THERE,
 * then play out the exchange on that square and take it again. The difference
 * is what the square yielded, and nothing else is counted.
 */
function pvWinsAt(fen, pv, target, plies) {
	if (!pv) return false;
	const moves = pv.split(/\s+/).slice(0, plies + 4);
	let pos;
	try {
		pos = positionFromFen(fen);
	} catch {
		return false;
	}
	const mover = pos.turn;
	const balance = (p) => {
		let w = 0;
		let b = 0;
		for (const sq of p.board.occupied) {
			const piece = p.board.get(sq);
			if (!piece || piece.role === 'king') continue;
			if (piece.color === 'white') w += VALUE[piece.role];
			else b += VALUE[piece.role];
		}
		return mover === 'white' ? w - b : b - w;
	};

	const play = (m) => {
		const from = parse(m.slice(0, 2));
		const to = parse(m.slice(2, 4));
		if (Number.isNaN(from) || Number.isNaN(to)) return false;
		try {
			pos.play({ from, to });
		} catch {
			return false;
		}
		return true;
	};

	// Walk to the first capture that lands on the target, inside the budget.
	let i = 0;
	for (; i < moves.length && i < plies; i++) {
		const to = moves[i].slice(2, 4);
		if (to === target && pos.board.get(parse(to)) !== undefined) break;
		if (!play(moves[i])) return false;
	}
	if (i >= moves.length || i >= plies) return false;

	const before = balance(pos);

	// The exchange on that square, and only that: keep playing while the line
	// keeps capturing there.
	if (!play(moves[i])) return false;
	for (i++; i < moves.length; i++) {
		if (moves[i].slice(2, 4) !== target) break;
		if (!play(moves[i])) return false;
	}

	return balance(pos) - before >= 100;
}

// ---------------------------------------------------------------------------
// The referee.
// ---------------------------------------------------------------------------
function ask(fen, depth = DEPTH) {
	return new Promise((resolve) => {
		const proc = spawn(ENGINE);
		let out = '';
		const timer = setTimeout(() => {
			proc.kill();
			resolve({ cp: 0, best: '', failed: true });
		}, 20_000);
		proc.stdout.on('data', (c) => {
			out += c.toString();
			if (out.includes('bestmove')) {
				clearTimeout(timer);
				proc.kill();
				let cp = 0;
				let pv = '';
				for (const l of out.split('\n')) {
					const m = /score (cp|mate) (-?\d+)/.exec(l);
					if (m) cp = m[1] === 'mate' ? (Number(m[2]) > 0 ? 9999 : -9999) : Number(m[2]);
					// Take the deepest line's PV; the last one printed is it.
					const p = /\bpv ((?:[a-h][1-8][a-h][1-8][qrbn]?\s*)+)/.exec(l);
					if (p) pv = p[1].trim();
				}
				resolve({ cp, pv, best: /bestmove (\S+)/.exec(out)?.[1] ?? '' });
			}
		});
		proc.stdin.write(`uci\nisready\nposition fen ${fen}\ngo depth ${depth}\n`);
	});
}

// ---------------------------------------------------------------------------
// Run.
// ---------------------------------------------------------------------------
let rngState = 20260822;
const rng = () => {
	rngState = (rngState * 1103515245 + 12345) & 0x7fffffff;
	return rngState / 0x7fffffff;
};

let tested = 0;
let agreed = 0;
let skipped = 0;
const wrong = [];

for (let i = 0; tested < COUNT && i < COUNT * 12; i++) {
	const fen = randomPosition(rng);
	let pos;
	try {
		pos = positionFromFen(fen);
		if (pos.isCheck()) continue;
	} catch {
		continue;
	}

	const squares = targets(fen);
	if (!squares.length) continue;
	const target = squares[Math.floor(rng() * squares.length)];

	let mine;
	try {
		mine = contest(fen, target);
	} catch {
		continue;
	}

	// The claim under test, and the narrowest one the algorithm makes: is there
	// material to be won AT THIS SQUARE, with or without one move of build-up?
	//
	// Thresholded at a pawn so both sides of the comparison are answering the
	// same question. Without it a knot worth ten centipawns counted as a claim
	// against a referee that only recognises a pawn, and the disagreement was
	// about the threshold rather than about the chess.
	const claims = mine.verdict.kind === 'winnable' && mine.knot.value >= 100;

	// ------------------------------------------------------------------
	// The referee has to answer the SAME question. "Is White better here"
	// is not it — that was the old criterion, and it counted a rook hanging
	// on the other side of the board as agreement about this square.
	//
	// So: take the engine's principal variation, play it, and ask whether a
	// capture lands on the target square inside the first four plies and
	// the side that made it is up material by the end of it. That is the
	// engine's own opinion about this square, expressed in its own line.
	// ------------------------------------------------------------------
	const { pv, cp, failed } = await ask(fen);
	if (failed) continue;

	// Skip positions that are already decided by something else. In a position
	// where mate is on, the engine's line does not visit this square and the
	// referee cannot see the question — that is a limit of adjudicating by
	// principal variation, and dropping those positions is the honest response
	// to it rather than reading the silence as a disagreement. Counted and
	// reported below so the sample size is not quietly inflated.
	if (Math.abs(cp) > 600) {
		skipped++;
		continue;
	}

	const engineWins = pvWinsAt(fen, pv, target, 4);

	tested++;
	if (claims === engineWins) agreed++;
	else wrong.push({ fen, target, mine: mine.verdict.kind, why: mine.verdict.why, pv });

	if (tested % 10 === 0) process.stdout.write(`${agreed}/${tested} `);
}

console.log(`\n\nagreement: ${agreed}/${tested} = ${Math.round((agreed / tested) * 100)}%`);
console.log(`(${skipped} positions skipped: already decided, |eval| > 600cp)`);
console.log(`\nDisagreements (${wrong.length}), engine cp vs my verdict:\n`);
for (const w of wrong.slice(0, 12)) {
	console.log(`  ${w.fen}`);
	console.log(`    target ${w.target}  me: ${w.mine}  engine pv: ${w.pv}`);
	console.log(`    ${w.why}\n`);
}
