// The Lab's examples, generated by inverting the algorithm.
//
// ---------------------------------------------------------------------------
// Will:
//
//   "If the algorithm was working correctly then we should not have all these
//    erroneously constructed examples, because they would be generated by
//    inverting it."
//
// He is right, and this is that inversion. Every one of the seven presets in
// the Lab was hand-built by me to illustrate a mechanism, and every one of them
// was misconstructed — a pin that could be broken with tempo, a knight already
// one move from a fork, a pawn whose "attack" blocked the bishop behind it.
// That is what happens when the person who wrote the procedure also chooses the
// positions it will be judged on: the fixture inherits the error.
//
// So the positions are not chosen here at all. Random ones are generated, the
// algorithm is run on every square, Stockfish adjudicates, and the first
// position that lands in each CATEGORY is kept. The categories are the
// algorithm's own outputs — wins now, wins after one move, the prize walks, a
// defender arrives, a check interrupts, the defence is on loan — so the example
// set is a picture of what the procedure can say, and it cannot flatter it.
//
// Usage:  node scripts/invent.mjs [tries] > src/views/labPresets.generated.json
// ---------------------------------------------------------------------------

import { spawn } from 'node:child_process';
import { build } from 'esbuild';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const ENGINE = '/usr/games/stockfish';
const TRIES = Number(process.argv[2] ?? 400);
const DEPTH = 16; // the same depth test/adjudicate.test.ts uses, so the two cannot disagree by accident

const dir = mkdtempSync(join(tmpdir(), 'invent-'));
const entry = join(dir, 'entry.ts');
writeFileSync(
	entry,
	`export { contest, VALUE } from ${JSON.stringify(join(process.cwd(), 'src/domain/contest.ts'))};
	 export { positionFromFen } from ${JSON.stringify(join(process.cwd(), 'src/domain/chess.ts'))};`,
);
const outfile = join(dir, 'bundle.mjs');
await build({
	entryPoints: [entry],
	bundle: true,
	format: 'esm',
	outfile,
	platform: 'node',
	logLevel: 'silent',
});
const { contest, positionFromFen, VALUE } = await import(outfile);

const FILES = 'abcdefgh';
const sq = (f, r) => `${FILES[f]}${r + 1}`;
const parse = (s) => (Number(s[1]) - 1) * 8 + FILES.indexOf(s[0]);

// ---------------------------------------------------------------------------
// What we are looking for. One example of each thing the algorithm can say.
//
// The `want` predicate reads the algorithm's OUTPUT — never the position — so
// a category cannot be defined into existence by choosing a fixture that
// matches a hand-written description of it.
// ---------------------------------------------------------------------------
const CATEGORIES = [
	{
		key: 'now',
		title: 'It is simply hanging',
		want: (c) => c.verdict.kind === 'winnable' && c.knot.at === 0 && c.knot.value >= 200,
	},
	{
		key: 'build',
		title: 'One move of preparation, and it cannot be answered',
		want: (c) => c.verdict.kind === 'winnable' && c.knot.at === 1 && c.knot.value >= 150,
	},
	{
		key: 'pinned',
		title: 'It cannot run — something stands behind it',
		want: (c) =>
			c.verdict.kind === 'winnable' &&
			c.knot.value >= 150 &&
			// On the rung the verdict actually rests on, or the example shows a
			// mechanism the headline never mentions.
			(() => {
				const r = c.knot.rungs.find((x) => x.holds);
				return !!r && r.escapeTry?.answer?.at === 'elsewhere' && r.escapeTry.leaves >= 150;
			})(),
	},
	{
		key: 'escape',
		title: 'The count pays and the prize walks away',
		want: (c) =>
			c.verdict.kind === 'not-winnable' &&
			c.knot.rungs.some((r) => r.count >= 100 && r.spoilers[0]?.kind === 'escape'),
	},
	{
		key: 'defender',
		title: 'The count pays and a defender arrives in time',
		want: (c) =>
			c.verdict.kind === 'not-winnable' &&
			// The spoiler that LEADS has to be the one the category is named
			// after, or the example illustrates a different mechanism from the
			// one its title claims — which is how the hand-built set went wrong.
			c.knot.rungs.some((r) => r.count >= 100 && r.spoilers[0]?.kind === 'defender'),
	},
	{
		key: 'forcing',
		title: 'The count pays and a bigger threat interrupts',
		want: (c) =>
			c.verdict.kind === 'not-winnable' &&
			c.knot.rungs.some((r) => r.count >= 100 && r.spoilers[0]?.kind === 'forcing'),
	},
	{
		key: 'entangled',
		title: 'The defence is on loan from somewhere else',
		want: (c) =>
			c.verdict.kind === 'entangled' &&
			// The loan has to be worth something, and it has to be owed to a
			// square with a piece on it. The first candidate this category
			// produced was a knight "holding" the empty square it was about to
			// be captured on — a route cost wearing a duty's clothes.
			c.rows.some((r) => r.critical.some((x) => x.unit.duty >= 150 && x.foldWithout >= 150)),
	},
];

// ---------------------------------------------------------------------------
// Random positions. Deliberately dumb: kings with a shelter, a handful of
// pieces, roughly level material. Nothing here aims at any category.
// ---------------------------------------------------------------------------
let rngState = Number(process.argv[3] ?? 7717);
const rng = () => {
	rngState = (rngState * 1103515245 + 12345) & 0x7fffffff;
	return rngState / 0x7fffffff;
};

function randomPosition() {
	const board = new Map([
		['g1', 'K'],
		['g8', 'k'],
	]);
	for (const f of [5, 6, 7]) {
		board.set(sq(f, 1), 'P');
		board.set(sq(f, 6), 'p');
	}
	const roles = ['Q', 'R', 'R', 'B', 'B', 'N', 'N', 'P', 'P'];
	const n = 3 + Math.floor(rng() * 4);
	for (let i = 0; i < n; i++) {
		const role = roles[Math.floor(rng() * roles.length)];
		for (const [colour, side] of [
			['w', role],
			['b', role.toLowerCase()],
		]) {
			for (let t = 0; t < 40; t++) {
				const f = Math.floor(rng() * 8);
				const r = colour === 'w' ? 1 + Math.floor(rng() * 5) : 2 + Math.floor(rng() * 5);
				const key = sq(f, r);
				if (board.has(key)) continue;
				board.set(key, side);
				break;
			}
		}
	}
	const rows = [];
	for (let r = 7; r >= 0; r--) {
		let row = '';
		let gap = 0;
		for (let f = 0; f < 8; f++) {
			const p = board.get(sq(f, r));
			if (!p) gap++;
			else {
				if (gap) row += gap;
				gap = 0;
				row += p;
			}
		}
		if (gap) row += gap;
		rows.push(row);
	}
	return `${rows.join('/')} w - - 0 1`;
}

function ask(fen, depth = DEPTH) {
	return new Promise((resolve) => {
		const proc = spawn(ENGINE);
		let out = '';
		const timer = setTimeout(() => {
			proc.kill();
			resolve({ cp: 0, pv: '', failed: true });
		}, 20_000);
		proc.stdout.on('data', (c) => {
			out += c.toString();
			if (out.includes('bestmove')) {
				clearTimeout(timer);
				proc.kill();
				let cp = 0;
				let pv = '';
				for (const l of out.split('\n')) {
					const m = /score (cp|mate) (-?\d+)/.exec(l);
					if (m) cp = m[1] === 'mate' ? (Number(m[2]) > 0 ? 9999 : -9999) : Number(m[2]);
					const p = /\bpv ((?:[a-h][1-8][a-h][1-8][qrbn]?\s*)+)/.exec(l);
					if (p) pv = p[1].trim();
				}
				resolve({ cp, pv });
			}
		});
		proc.stdin.write(`uci\nisready\nposition fen ${fen}\ngo depth ${depth}\n`);
	});
}

/** The engine's opinion about this square, isolated to this square. */
function pvWinsAt(fen, pv, target, plies = 4) {
	if (!pv) return false;
	const moves = pv.split(/\s+/);
	let pos;
	try {
		pos = positionFromFen(fen);
	} catch {
		return false;
	}
	const mover = pos.turn;
	const balance = (p) => {
		let w = 0;
		let b = 0;
		for (const s of p.board.occupied) {
			const piece = p.board.get(s);
			if (!piece || piece.role === 'king') continue;
			if (piece.color === 'white') w += VALUE[piece.role];
			else b += VALUE[piece.role];
		}
		return mover === 'white' ? w - b : b - w;
	};
	const play = (m) => {
		try {
			pos.play({ from: parse(m.slice(0, 2)), to: parse(m.slice(2, 4)) });
			return true;
		} catch {
			return false;
		}
	};
	let i = 0;
	for (; i < moves.length && i < plies; i++) {
		if (moves[i].slice(2, 4) === target && pos.board.get(parse(target)) !== undefined) break;
		if (!play(moves[i])) return false;
	}
	if (i >= moves.length || i >= plies) return false;
	const before = balance(pos);
	if (!play(moves[i])) return false;
	for (i++; i < moves.length && moves[i].slice(2, 4) === target; i++) {
		if (!play(moves[i])) return false;
	}
	return balance(pos) - before >= 100;
}

// ---------------------------------------------------------------------------
// Run.
// ---------------------------------------------------------------------------
const found = new Map();

for (let t = 0; t < TRIES && found.size < CATEGORIES.length; t++) {
	const fen = randomPosition();
	let pos;
	try {
		pos = positionFromFen(fen);
		if (pos.isCheck()) continue;
	} catch {
		continue;
	}

	// Every black piece is a candidate prize. No square is preferred.
	const squares = [];
	for (let f = 0; f < 8; f++) {
		for (let r = 0; r < 8; r++) {
			const key = sq(f, r);
			const piece = pos.board.get(parse(key));
			if (piece && piece.color === 'black' && piece.role !== 'king') squares.push(key);
		}
	}

	for (const target of squares) {
		let c;
		try {
			c = contest(fen, target);
		} catch {
			continue;
		}

		const hit = CATEGORIES.find((cat) => !found.has(cat.key) && cat.want(c));
		if (!hit) continue;

		// Adjudicate before keeping it. A category that only the algorithm
		// believes in is exactly what this script exists to avoid.
		const { cp, pv, failed } = await ask(fen);
		if (failed || Math.abs(cp) > 600) continue;
		const engineWins = pvWinsAt(fen, pv, target);
		const claims = c.verdict.kind === 'winnable' && c.knot.value >= 100;
		if (claims !== engineWins) continue;

		found.set(hit.key, {
			key: hit.key,
			title: hit.title,
			fen,
			square: target,
			claim: claims ? 'wins' : 'nothing',
			verdict: c.verdict.kind,
			why: c.verdict.why,
			engine: cp,
		});
		process.stderr.write(`found ${hit.key} at try ${t}\n`);
		break;
	}
}

const missing = CATEGORIES.filter((c) => !found.has(c.key)).map((c) => c.key);
if (missing.length) process.stderr.write(`not found in ${TRIES} tries: ${missing.join(', ')}\n`);

console.log(JSON.stringify([...found.values()], null, '\t'));
